cart/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'cart'
urlpatterns = [
  path('<pk>/add_to_cart/', views.add_to_cart, name='add_to_cart'),
  path('<pk>/remove_from_cart/', views.remove_from_cart, name = 'remove_from_cart'),
  path('', views.get_cart, name='cart'),
  path('generate_payment/', login_required(views.generate_payment), name='generate_payment'),
]

orders/urls.py
from django.urls import path
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from . import views
app_name = 'orders'

urlpatterns = [
    path('', login_required(views.my_orders), name='my_orders'),
    path('all_orders', staff_member_required(views.all_orders), name='all_orders'),
    path('<pk>/update', staff_member_required(views.OrderUpdateView.as_view()), name='update')
]

vestecam/urls.py
from django.contrib import admin
from django.urls import include, path
import cart
urlpatterns = [
    path('', include('staticpages.urls'), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('process_payment', cart.views.process_payment, name='process_payment'),
]

cart/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType
from django.conf import settings
class Cart(models.Model):
    creation_date = models.DateTimeField(verbose_name=_('creation date'))
    checked_out = models.BooleanField(default=False, verbose_name=_('checked out'))

    class Meta:
        verbose_name = _('cart')
        verbose_name_plural = _('carts')
        ordering = ('-creation_date',)



class ItemManager(models.Manager):
    def get(self, *args, **kwargs):
        if 'product' in kwargs:
            kwargs['content_type'] = ContentType.objects.get_for_model(type(kwargs['product']))
            kwargs['object_id'] = kwargs['product'].pk
            del(kwargs['product'])
        return super(ItemManager, self).get(*args, **kwargs)

    def filter(self, *args, **kwargs):
        if 'product' in kwargs:
            kwargs['content_type'] = ContentType.objects.get_for_model(type(kwargs['product']))
            kwargs['object_id'] = kwargs['product'].pk
            del(kwargs['product'])
        return super(ItemManager, self).filter(*args, **kwargs)


class Item(models.Model):
    cart = models.ForeignKey(Cart, verbose_name=_('cart'), on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name=_('quantity'))
    unit_price = models.DecimalField(max_digits=18, decimal_places=2, verbose_name=_('unit price'))
    # product as generic relation
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()

    objects = ItemManager()

    class Meta:
        verbose_name = _('item')
        verbose_name_plural = _('items')
        ordering = ('cart',)

    def __unicode__(self):
        return u'%d units of %s' % (self.quantity, self.product.__class__.__name__)

    def total_price(self):
        return self.quantity * self.unit_price
    total_price = property(total_price)

    # product
    def get_product(self):
        return self.content_type.get_object_for_this_type(pk=self.object_id)

    def set_product(self, product):
        self.content_type = ContentType.objects.get_for_model(type(product))
        self.object_id = product.pk

    product = property(get_product, set_product)

class Order(models.Model):
    id = models.IntegerField(primary_key=True)
    buyer = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    items = models.TextField()
    valor = models.DecimalField(max_digits=8, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True)
    pago = models.BooleanField(default=True)
    entregue = models.BooleanField(default=False)

orders/models.py
from django.db import models

# Create your models here.

cart/views.py
# Create your views here.
from cart.cart import Cart
from products.models import Product
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
import mercadopago
from django.views.decorators.csrf import csrf_exempt
from . import models
from django.contrib.auth.models import User
import json
def add_to_cart(request, pk):
    product = Product.objects.get(id=pk)
    cart = Cart(request)
    if product.desconto:
      valor = product.valor_com_desconto
    else:
        valor = product.valor
    cart.add(product, valor, quantity=1)
    print(cart.summary())
    return HttpResponseRedirect(reverse('products:index'))

def remove_from_cart(request, pk):
    product = Product.objects.get(id=pk)
    cart = Cart(request)
    cart.remove(product)
    return HttpResponseRedirect(reverse('cart:cart'))

def get_cart(request):
    return render(request, 'cart/cart.html', {'cart': Cart(request)})

def generate_payment(request):
    return render(request, 'cart/generate_payment.html', {'cart': Cart(request)})

@csrf_exempt
def process_payment(request):
    
    sdk = mercadopago.SDK("APP_USR-2180497889937881-112909-4d49264e0c5960400250cb46b4c39a4e-1125665108")
    request_values = json.loads(request.body)
    payment_data = {
        "transaction_amount": float(request_values["transaction_amount"]),
        "token": request_values["token"],
        "installments": int(request_values["installments"]),
        "payment_method_id": request_values["payment_method_id"],
        "issuer_id": request_values["issuer_id"],
        "payer": {
            "email": request_values["payer"]["email"],
            "identification": {
                "type": request_values["payer"]["identification"]["type"], 
                "number": request_values["payer"]["identification"]["number"]
            }
        }
    }

    payment_response = sdk.payment().create(payment_data)
    payment = payment_response["response"]

    print("status =>", payment["status"])
    print("status_detail =>", payment["status_detail"])
    print("id =>", payment["id"])
    items = ''
    for i in Cart(request):
        items += (str(i.quantity) + 'x ' + str(i.product.nome) + '\n')
    user_id = request.user.id
    valor = Cart(request).summary()
    order_obj = models.Order(buyer=User.objects.get(id=user_id), valor=valor, items=items)
    order_obj.save()
    Cart(request).new(request)
    return render(request, 'cart/cart.html', {'cart': Cart(request)})

orders/views.py
from django.shortcuts import render
from cart.models import Order
from django.views.generic.edit import UpdateView
def my_orders(request):
  user_id = request.user.id
  my_orders = Order.objects.filter(buyer_id=user_id).all()
  print(my_orders)
  return render(request, 'orders/my_orders.html', context={ 'orders': my_orders })

def all_orders(request):
  all_orders = Order.objects.all()
  return render(request, 'orders/all_orders.html', context={'orders': all_orders})

class OrderUpdateView(UpdateView):
  model = Order
  fields = ['pago','entregue']
  success_url = "/orders/"

cart/templates/cart/cart.html
{% extends 'base.html' %}
{% block title %}
Carrinho
{% endblock %}

{% block content %}
    <table class="table table-striped table-dark">
        <thead>
            <tr>
                <th scope="col">Produto</th>
                <th scope="col">Quantidade</th>
                <th scope="col">Valor Unitário</th>
                <th scope="col">Valor Total</th>
                <th scope="col">Remover</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart %}
            <tr>
                <td><img style="width:40px; margin-right: 10px; border-style: solid; border-color: black;" src="{{ item.product.imagem_url}}" alt="">{{ item.product.nome }}</td>
                <td>{{ item.quantity }}</td>
                    {% if item.product.desconto %}
                        <td>R$ {{ item.product.valor_com_desconto }}</td>
                        <td>R$ {% widthratio item.product.valor_com_desconto 1 item.quantity %}</td>
                    {% else %}
                        <td>R$ {% widthratio item.product.valor 1 item.quantity %}</td>
                    {% endif %}
                        <td>
                            <a class="btn btn-outline-danger btn-sm" href="{% url 'cart:remove_from_cart' item.product.id %}"><i class="fa-solid fa-trash"></i></a>
                        </td>
            </tr>
            {% empty %}
                <td>No momento não há nenhum produto no carrinho.</td>
            {% endfor %}
            <td>Total: R$ {% if cart.summary == None %} 0,00 {% else %} {{ cart.summary|floatformat:2 }} {% endif %}</td>
        </tbody>
    </table>
    <a class="btn btn-primary" href="{% url 'cart:generate_payment' %}">Finalizar e ir para o pagamento</a>
{% endblock %}

cart/templates/cart/generate_payment.html
{% extends 'base.html' %}

{% block title %}
Pagamento
{% endblock %}

{% block content %}
<h2>Valor total: R$ {{ cart.summary|floatformat:2 }} </h1>
<div id="cardPaymentBrick_container"></div>
<script src="https://sdk.mercadopago.com/js/v2"></script>
<script>
  const mp = new MercadoPago('APP_USR-702a3f1e-d268-4e3b-8a2a-6887dfd34a91');
  const bricksBuilder = mp.bricks();
  const renderCardPaymentBrick = async (bricksBuilder) => {
    const settings = {
      initialization: {
        amount: 1.0, // valor total a ser pago
      },
      callbacks: {
        onReady: () => {
          /*
            Callback chamado quando o Brick estiver pronto.
            Aqui você pode ocultar loadings do seu site, por exemplo.
          */
        },
        onSubmit: (cardFormData) => {
          // callback chamado o usuário clicar no botão de submissão dos dados

          // ejemplo de envío de los datos recolectados por el Brick a su servidor
          return new Promise((resolve, reject) => {
              fetch("/process_payment", { 
                  method: "POST",
                  headers: {
                      "Content-Type": "application/json",
                  },
                  body: JSON.stringify(cardFormData)
              })
              .then((response) => {
                  // receber o resultado do pagamento
                  resolve();
              })
              .catch((error) => {
                  // lidar com a resposta de erro ao tentar criar o pagamento
                  reject();
              })
            });
        },
        onError: (error) => { 
          // callback chamado para todos os casos de erro do Brick
          console.error(error);
        },
      },
    };
    const cardPaymentBrickController = await bricksBuilder.create('cardPayment', 'cardPaymentBrick_container', settings);
    };
  renderCardPaymentBrick(bricksBuilder);
</script>
{% endblock %}

cart/templates/cart/order_form.html
<form method="post">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Save">
</form>