cart/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'cart'
urlpatterns = [
  path('<pk>/add_to_cart/', views.add_to_cart, name='add_to_cart'),
  path('<pk>/remove_from_cart/', views.remove_from_cart, name = 'remove_from_cart'),
  path('', views.get_cart, name='cart'),
  path('generate_payment/', login_required(views.generate_payment), name='generate_payment'),
]

orders/urls.py
from django.urls import path
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from . import views
app_name = 'orders'

urlpatterns = [
    path('', login_required(views.my_orders), name='my_orders'),
    path('all_orders', staff_member_required(views.all_orders), name='all_orders'),
    path('<pk>/update', staff_member_required(views.OrderUpdateView.as_view()), name='update')
]

vestecam/urls.py
from django.contrib import admin
from django.urls import include, path
import cart
urlpatterns = [
    path('', include('staticpages.urls'), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('process_payment', cart.views.process_payment, name='process_payment'),
]

orders/models.py
from django.db import models

# Create your models here.

orders/views.py
from django.shortcuts import render
from cart.models import Order
from django.views.generic.edit import UpdateView
def my_orders(request):
  user_id = request.user.id
  my_orders = Order.objects.filter(buyer_id=user_id).all()
  print(my_orders)
  return render(request, 'orders/my_orders.html', context={ 'orders': my_orders })

def all_orders(request):
  all_orders = Order.objects.all()
  return render(request, 'orders/all_orders.html', context={'orders': all_orders})

class OrderUpdateView(UpdateView):
  model = Order
  fields = ['pago','entregue']
  success_url = "/orders/"

orders/templates/orders/all_orders.html
{% extends 'base.html' %}

{% block title %}
Gerenciar Pedidos
{% endblock %}

{% block content %}
<h3>Gerenciar Pedidos</h3>
<table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Comprador</th>
      <th scope="col">Produtos</th>
      <th scope="col">Valor</th>
      <th scope="col">Data da compra</th>
      <th scope="col">Status</th>
      <th scope="col">Editar</th>
    </tr>
  </thead>
  <tbody>
    {% for order in orders %}
    <tr>
      <th scope="row">{{ order.id }}</th>
      <td>{{ order.buyer.first_name }} {{ order.buyer.last_name }}</td>
      <td>{{ order.items }}</td>
      <td>R$ {{ order.valor }}</td>
      <td>{{ order.timestamp }}</td>
      <td>{% if not order.pago %}Não pago {% elif order.entregue %}Entregue {% else %} Pago {% endif %}</td>
      <td>
        <a class="btn btn-outline-success btn-sm" href="{% url 'orders:update' order.id %}"><i class="fa-solid fa-pencil"></i></a>
      </td>
    
    </tr>
    {% empty %}
      <li>Não há pedidos.</li>
    {% endfor %}

  </tbody>
</table>
{% endblock %}

orders/templates/orders/my_orders.html
{% extends 'base.html' %}

{% block title %}
Meus Pedidos
{% endblock %}

{% block content %}
<h3>Meus Pedidos</h3>
<table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Produtos</th>
      <th scope="col">Valor</th>
      <th scope="col">Data da compra</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <tbody>
    {% for order in orders %}
    <tr>
      <th scope="row">{{ order.id }}</th>
      <td>{{ order.items }}</td>
      <td>R$ {{ order.valor }}</td>
      <td>{{ order.timestamp }}</td>
      <td>{% if not order.pago %}Não pago {% elif order.entregue %}Entregue {% else %} Pago {% endif %}</td>
    </tr>
    {% empty %}
      <li>Você não possui pedidos.</li>
    {% endfor %}

  </tbody>
</table>
{% endblock %}