cart/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'cart'
urlpatterns = [
  path('<pk>/add_to_cart/', views.add_to_cart, name='add_to_cart'),
  path('<pk>/remove_from_cart/', views.remove_from_cart, name = 'remove_from_cart'),
  path('', views.get_cart, name='cart'),
  path('generate_payment/', login_required(views.generate_payment), name='generate_payment'),
]

orders/urls.py
from django.urls import path
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from . import views
app_name = 'orders'

urlpatterns = [
    path('', login_required(views.my_orders), name='my_orders'),
    path('all_orders', staff_member_required(views.all_orders), name='all_orders'),
    path('<pk>/update', staff_member_required(views.OrderUpdateView.as_view()), name='update')
]

products/urls.py
from django.urls import path
from . import views
from django.contrib.admin.views.decorators import staff_member_required
app_name = 'products'

urlpatterns = [
  path('', views.ProductListView.as_view(), name='index'),
  path('<pk>/delete/', views.ProductDeleteView.as_view(), name='delete'),
  path('create/', views.ProductCreateView.as_view(), name='create'),
  path('<pk>/update', staff_member_required(views.ProductUpdateView.as_view()), name='update')
]

vestecam/urls.py
from django.contrib import admin
from django.urls import include, path
import cart
urlpatterns = [
    path('', include('staticpages.urls'), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('process_payment', cart.views.process_payment, name='process_payment'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
      {% block title %}{% endblock %} | VesteCAM
  </title>
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <script src="https://kit.fontawesome.com/5445411d6c.js" crossorigin="anonymous"></script>
</head>

<body>
  <header id="cabecalho-principal">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'index' %}">
            <img src="https://www.cam.poli.usp.br/assets/img/LOGOCAMLINDO.png" alt="Bootstrap" width="30" height="24">
            VesteCAM</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link {% if request.path == url %} active {% endif %}" href="{% url 'index' %}">Home</a>
              <a class="nav-link" href="{% url 'about' %}">Sobre</a>
              <a class="nav-link" href="{% url 'products:index' %}">Produtos</a>
              <a class="nav-link" href="{% url 'cart:cart' %}">Meu Carrinho</a>
              <a class="nav-link" href="{% url 'orders:my_orders' %}">Meus Pedidos</a>
              {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'orders:all_orders' %}">Gerenciar Pedidos</a>
                <a class="nav-link" href="{% url 'logout' %}">Logado com {{ user.username }} (Fazer log out)</a>
              {% else %}
                <a class="nav-link" href="{% url 'login' %}">Log in</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>

  </header>
  <main id="conteiner-principal">
    {% block content %}
    {% endblock content %}
  </main>
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
      <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
        <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"/></svg>
      </a>
      <span class="mb-3 mb-md-0 text-muted">&copy; 2022 CAM POLI USP</span>
    </div>

    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <li class="ms-3"><a class="text-muted" href="https://www.facebook.com/cam.poli.usp"><i class="fa-brands fa-facebook-f"></i></a></li>
      <li class="ms-3"><a class="text-muted" href="https://www.instagram.com/campoliusp/"><i class="fa-brands fa-instagram"></i></a></li>
    </ul>
  </footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  
</body>

</html>