cart/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'cart'
urlpatterns = [
  path('<pk>/add_to_cart/', views.add_to_cart, name='add_to_cart'),
  path('<pk>/remove_from_cart/', views.remove_from_cart, name = 'remove_from_cart'),
  path('', views.get_cart, name='cart'),
  path('generate_payment/', login_required(views.generate_payment), name='generate_payment'),
]

products/urls.py
from django.urls import path
from . import views
from django.contrib.admin.views.decorators import staff_member_required
app_name = 'products'

urlpatterns = [
  path('', views.ProductListView.as_view(), name='index'),
  path('<pk>/delete/', views.ProductDeleteView.as_view(), name='delete'),
  path('create/', views.ProductCreateView.as_view(), name='create'),
  path('<pk>/update', staff_member_required(views.ProductUpdateView.as_view()), name='update')
]

vestecam/urls.py
from django.contrib import admin
from django.urls import include, path
import cart
urlpatterns = [
    path('', include('staticpages.urls'), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('process_payment', cart.views.process_payment, name='process_payment'),
]

products/models.py
from django.db import models
from django.conf import settings

class Product(models.Model):
  id = models.AutoField(primary_key=True)
  nome = models.CharField(max_length=255)
  descricao = models.CharField(max_length=255)
  imagem_url = models.URLField(max_length=200, null=True)
  valor = models.DecimalField(max_digits=8,decimal_places=2)
  valor_com_desconto = models.DecimalField(max_digits=8,decimal_places=2)
  desconto = models.BooleanField()
  ativo = models.BooleanField()
  quantidade = models.IntegerField()
  tamanho = models.CharField(max_length=255, null=True)
  def __str__(self):
        return f'{self.nome} ({self.tamanho})'

products/views.py
from django.shortcuts import render
from django.utils import timezone
from django.views.generic.list import ListView
from django.views.generic.edit import DeleteView, UpdateView, CreateView
from .models import Product
import requests
from cart.cart import Cart

class ProductListView(ListView):
  model = Product
  context_object_name = 'all_products'
  template_name = 'products/index.html'
  extra_context={}

class ProductUpdateView(UpdateView):
  model = Product
  fields = ['nome', 'descricao', 'imagem_url', 'valor', 'valor_com_desconto', 'desconto', 'ativo', 'quantidade', 'tamanho']
  success_url = "/products/"

class ProductDeleteView(DeleteView):
  model = Product
  success_url ="/products/"
  template_name = "products/delete_confirm.html"
  
class ProductCreateView(CreateView):
  model = Product
  fields = ['nome', 'descricao', 'imagem_url', 'valor', 'valor_com_desconto', 'desconto', 'ativo', 'quantidade', 'tamanho']
  success_url = "/products/"

products/templates/products/delete_confirm.html
{% if user.is_staff %}
<form method="post">{% csrf_token %}
     
 
 
 
  <p>Are you sure you want to delete "{{ object }}"?</p>
   
   
   
   
      <input type="submit" value="Confirm">
  </form>
{% endif %}

products/templates/products/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Todos os Produtos</h2>
{% if user.is_staff %}
<a href="{% url 'products:create' %}" class="btn btn-primary"><i class="fa-solid fa-cart-shopping"></i> + Adicionar novo produto</a>
{% endif %}
<section class="row row-cols-1 row-cols-md-3 g-4" style="margin: auto;">
{% for product in all_products %}
<div class="card" style="width: 18rem;">
  <img src="{{ product.imagem_url }}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{ product.nome }}</h5>
    <p class="card-text">{{ product.descricao }}</p>
    <p class="card-text">Quantidade em estoque: {{ product.quantidade }}</p>
    <p class="card-text">Tamanho: {{ product.tamanho }}</p>
    {% if product.desconto %}
    <p class="card-text"><s>R$ {{ product.valor }}</s></p>
    <p class="card-text"> R$ {{ product.valor_com_desconto }}</p>
    {% else %}
    <p class="card-text"> R$ {{ product.valor }}</p>
    {% endif %}
    {% if product.ativo %}
    <a href="{% url 'cart:add_to_cart' product.id %}" class="btn btn-primary"><i class="fa-solid fa-cart-shopping"></i> Adicionar ao carrinho</a>
    {% else %}
    <a href="#" class="btn btn-primary disabled">Indisponível</a>
    {% endif %}
    {% if user.is_staff %}
      <a class="btn btn-outline-danger btn-sm" href="{% url 'products:delete' product.id %}"><i class="fa-solid fa-trash"></i></a>
      <a class="btn btn-outline-success btn-sm" href="{% url 'products:update' product.id %}"><i class="fa-solid fa-pencil"></i></a>
    {% endif %}
  </div>
</div>
{% empty %}
    <li>No momento não temos nenhum produto disponível.</li>
{% endfor %}
</section>
</ul>
{% endblock %}

products/templates/products/product_form.html
<form method="post">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Save">
</form>

products/templates/products/product_update_form.html
<form method="post">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Update">
</form>